version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports: 
      - 3306:3306
    networks:
      - stack
    environment:
      MYSQL_ROOT_PASSWORD: cat_root
      MYSQL_DATABASE: los_gatos
      MYSQL_USER: cat
      MYSQL_PASSWORD: cat

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - stack
    environment:
      - discovery.type=single-node

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports: 
      - 3000:3000
    networks:
      - stack

  losgatos:
    image: italosp/losgatos:0.0.2
    ports: 
      - 5000:5000
    networks:
      - stack

volumes:
    db_data: 
    es_data:
    grafana_data:

networks:
  stack: